#!/usr/bin/env bash

set -e
cd /_build
chown -R makepkg:users /_build

if [ -f "._config" ]; then
	source "._config"
fi

sudo -u makepkg \
		PACKAGER="Salif Mehmed <mail@salif.eu>" \
		SRCDEST=/home/makepkg/build/srcdest \
		SRCPKGDEST=/home/makepkg/build/srcpkgdest \
		LOGDEST=/home/makepkg/build/logdest \
		BUILDDIR=/home/makepkg/build/build \
		PKGDEST=/home/makepkg/build/out \
		PKGEXT=".pkg.tar.zst" \
		SRCEXT=".src.tar.zst" \
		_PASS="$_PASS" \
		makepkg --noconfirm ${_NODEPS:-'-s'} -f
sudo -u makepkg makepkg --printsrcinfo > .SRCINFO
mv /home/makepkg/build/out/* /_pkg
